name: Update Json API

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependências
        run: pip install requests

      - name: Atualizar JSON
        run: |
          python update.py

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dados.json
          git commit -m "Atualizando dados.json automaticamente"
          git push
